// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/employees.proto

package employees

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/micro/v3/service/api"
	client "github.com/micro/micro/v3/service/client"
	server "github.com/micro/micro/v3/service/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Employees service

func NewEmployeesEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Employees service

type EmployeesService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Employees_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Employees_PingPongService, error)
}

type employeesService struct {
	c    client.Client
	name string
}

func NewEmployeesService(name string, c client.Client) EmployeesService {
	return &employeesService{
		c:    c,
		name: name,
	}
}

func (c *employeesService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Employees.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeesService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Employees_StreamService, error) {
	req := c.c.NewRequest(c.name, "Employees.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &employeesServiceStream{stream}, nil
}

type Employees_StreamService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type employeesServiceStream struct {
	stream client.Stream
}

func (x *employeesServiceStream) Close() error {
	return x.stream.Close()
}

func (x *employeesServiceStream) Context() context.Context {
	return x.stream.Context()
}

func (x *employeesServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *employeesServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *employeesServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *employeesService) PingPong(ctx context.Context, opts ...client.CallOption) (Employees_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Employees.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &employeesServicePingPong{stream}, nil
}

type Employees_PingPongService interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type employeesServicePingPong struct {
	stream client.Stream
}

func (x *employeesServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *employeesServicePingPong) Context() context.Context {
	return x.stream.Context()
}

func (x *employeesServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *employeesServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *employeesServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *employeesServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Employees service

type EmployeesHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Employees_StreamStream) error
	PingPong(context.Context, Employees_PingPongStream) error
}

func RegisterEmployeesHandler(s server.Server, hdlr EmployeesHandler, opts ...server.HandlerOption) error {
	type employees interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Employees struct {
		employees
	}
	h := &employeesHandler{hdlr}
	return s.Handle(s.NewHandler(&Employees{h}, opts...))
}

type employeesHandler struct {
	EmployeesHandler
}

func (h *employeesHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.EmployeesHandler.Call(ctx, in, out)
}

func (h *employeesHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.EmployeesHandler.Stream(ctx, m, &employeesStreamStream{stream})
}

type Employees_StreamStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type employeesStreamStream struct {
	stream server.Stream
}

func (x *employeesStreamStream) Close() error {
	return x.stream.Close()
}

func (x *employeesStreamStream) Context() context.Context {
	return x.stream.Context()
}

func (x *employeesStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *employeesStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *employeesStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *employeesHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.EmployeesHandler.PingPong(ctx, &employeesPingPongStream{stream})
}

type Employees_PingPongStream interface {
	Context() context.Context
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type employeesPingPongStream struct {
	stream server.Stream
}

func (x *employeesPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *employeesPingPongStream) Context() context.Context {
	return x.stream.Context()
}

func (x *employeesPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *employeesPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *employeesPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *employeesPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
